# serverConfig
server:
  port: 8100
  servlet:
    context-path: /
# redisConfig
spring:
  application:
    name: java-libgolang
# logConfig
logging:
  file:
    path: ./log
  level:
    org:
    springframework:
      context: DEBUG
    com:
      libgolang: DEBUG