# serverConfig
server:
  port: 8100
  servlet:
    context-path: /
# redisConfig
spring:
  application:
    name: java-libgolang
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 1000
    lettuce:
      pool:
        max-idle: 8
        max-active: 32
        max-wait: 1000
        min-idle: 8
  # dataSource
  datasource:
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    # HikariCP 自定义配置，对应 HikariConfig 配置属性类
    hikari:
      minimum-idle: 10
      maximum-pool-size: 10
  # jpa
  jpa:
    hibernate:
      ddl-auto: update
  #spring:jpa:show-sql=true
# mybatisConfig
#开启sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-enums-package: com.client.enums
# nacos
nacos:
  config:
    server-addr: 127.0.0.1:8848
    namespace: c4b22db0-2d02-4c27-995f-96acaf4bd993
  discovery:
    server-addr: 127.0.0.1:8848
    namespace: c4b22db0-2d02-4c27-995f-96acaf4bd993
# logConfig
logging:
  file:
    path: ./log
  level:
    org:
    springframework:
      context: DEBUG
    com:
      libgolang: DEBUG
## grpc 配置
grpc:
  server:
    port: 8101
    address: 127.0.0.1